remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter

sass:
  style: compressed

gem "github-pages", group: :jekyll_plugins

title: Flavour - Find Your Flavour

description: Support our vertically integrated bespoke high-tech knitting company and experience the future of fashion.

