remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter

sass:
  style: compressed

gem "github-pages", group: :jekyll_plugins

title: Flavournomics - Find Your Flavour of economics

description: My personal Blog
